export const activities = [
    "speaking about the sun",
    "looking at the moon",
    "sitting next to the lake",
    "telling a secret",
    "having a party",
    "dancing",
    "singing a song",
    "painting a picture",
    "writing a poem",
    "sharing a laugh",
    "telling a joke",
    "watching the clouds",
    "throwing a frisbee",
    "flying a kite",
    "building a sandcastle",
    "jumping in puddles",
    "racing each other",
    "whispering a wish",
    "lighting a candle",
    "making a wish",
    "hugging goodbye",
    "playing chess",
    "baking cookies",
    "watching a movie",
    "building a fort",
    "practicing yoga",
    "gardening",
    "teaching each other something",
    "trying new hairstyles",
    "solving a puzzle",
    "telling ghost stories",
    "Watching a parade",
    "drawing in the sand",
    "learning a dance",
    "catching fireflies",
    "skipping stones",
    "learning magic"
];

export const times = [
    "day",
    "night",
    "moon",
    "sun"
];